services:
  obsync:
    image: ghcr.io/kruceo/obsync:latest
    restart: unless-stopped
    ports:
      - "4377:4377"
    environment:
      SYNC_PASSWORD: yourpassword
      JWT_SECRET: yoursecret
    volumes:
      - obsync_data:/data

volumes:
  obsync_data:
